/**
 * Strings for Localization
 * STRING: 'Value of String'
 */
export default {
  APP_NAME: 'OneMV',
  SELECT_STATE: 'Select State',
  SELECT_SERVICE: 'Select Service',
  SWITCH_SERVICE: 'Switch Service',
  LOGIN_WITH_FACEBOOK: 'Login with Facebook',
  LOGIN_WITH_GOOGLE: 'Login with Google',
  LOGIN_WITH_ONEMV: 'Login with OneMV',
  NEXT: 'Next',
  NEED_HELP: 'Need Help?',
  POWERED_BY: 'Powered by',
  COPYRIGHT: '\u00A9 2019 MV TRANSPORTATION INC.',
  APP_VERSION: 'App Version',
  MV_COMPANY_NAME: 'MV Transportation Inc. ',
  MV_COMPANY_LINK: 'mvtransit.com ',
  HOME: 'Home',
  MY_TRIPS: 'My Trips',
  ACCOUNT: 'Account',
  MENU: 'Menu',
  WHATS_NEW: 'What\'s New',
  TODAY: 'Today',
  FUTURE: 'Future',
  RECENT: 'Recent',
  SIGN_OUT: 'Sign Out',
  TRIP_DETAILS: 'Trip Details',
  MAP_VIEW: 'Map View',
  RATE_THIS_TRIP: 'Rate this Trip',
  HELP_US_IMPROVE_EXPERIENCE: 'Help us improve experience!',
  SHARE_YOUR_EXPERIENCE: 'Share your experience!',
  COMMENTS: 'Comments',
  SUBMIT_RATING: 'Submit Rating',
  WHAT_CAN_WE_IMPROVE: 'What can we improve?',
  TRIP_OVERVIEW: 'Trip Overview',
  CLIENT_ID: 'Client ID',
  DATE_OF_BIRTH: 'Date of Birth',
  VERIFY: 'Verify',
  LOADING: 'Loading',
  ERROR: 'Sorry, Something went wrong.',
  NO_POLICIES: 'No Policies',
  NO_WHATS_NEW: 'Nothing New',
  POLICY_PAGE_TITLE: 'Policies',
  POLICY_PAGE_LOADING_ERROR: '',
  POLICY_PAGE_NO_DATA: 'No Policies',
  SUPPORT_PAGE_TITLE: 'Support',
  SUPPORT_PAGE_LOADING_ERROR: '',
  SUPPORT_PAGE_NO_DATA: 'No Support Information',
  NO_UPCOMING_TRIPS_FOUND: 'No upcoming trips found',
  YOU_HAVE_NO_RESERVATIONS_FOR_TODAY: 'You have no reservations for today',
  YOU_HAVE_NO_RECENT_RESERVATIONS: 'You have no recent reservations',
  YOU_HAVE_NO_FUTURE_RESERVATIONS: 'You have no future reservations',
  VERIFICATION_NUMBER: 'Verification Number',
  DATE_PLACEHOLDER: 'MM/DD/YYYY',
  VERIFICATION: 'Verification',
  CLIENT_VERIFICATION: 'Client Verification',
  PASSENGER: 'Passenger',
  CONFIRMATION_NO: 'Confirmation No.',
  PCA: 'PCA',
  MOBILITY_AIDS: 'Mobility Aids',
  SCHEDULED: 'Scheduled',
  UNSCHEDULED: 'Unscheduled',
  COMPLETED: 'Completed',
  NO_SHOW: 'No Show',
  CANCELLED: 'Cancelled',
  PLEASE_SELECT_A_STATE: 'Please select a state',
  PLEASE_SELECT_YOUR_SERVICE: 'Please select your service',
  REQUIRED: 'Required',
  INVALID_VERIFICATION_NUMBER: 'Invalid verification number',
  DATE_DID_NOT_MATCH: 'Date did not match',
  YOUR_CLIENT_ID_OR_BIRTH_DATE_IS_INVALID: 'Your Client ID or Birth Date is Invalid.',
  INVALID_ACCOUNT: 'Invalid Account',
  PLEASE_TRY_AGAIN: ' Please try again.',
  YOUR_CLIENT_ID: 'Your Client ID',
  UNABLE_TO_LOAD_TRIPS: 'Unable to Load Trips',
  REFRESH: 'Refresh',
  OOPS_WE_ARE_UNABLE_TO_SUBMIT_YOUR_RATING: 'Oops, we are unable to submit you rating...',
  RETRY: 'Retry',
  SUBMIT_LATER: 'Submit Later',
  CONTACT_CUSTOMER_SUPPORT: 'Contact customer support',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  MIDDLE_NAME: 'Middle Name',
  ONEMV_LOGIN_LOGIN_HEADER: 'Login',
  ONEMV_LOGIN_EMAIL: 'Email',
  ONEMV_LOGIN_EMAIL_PH: 'Your Email',
  ONEMV_LOGIN_PASSWORD: 'Password',
  ONEMV_LOGIN_PASSWORD_PH: 'Your Password',
  ONEMV_LOGIN_LOGIN_BUTTON: 'Login',
  ONEMV_LOGIN_REGISTER_LINK: 'Register',
  ONEMV_LOGIN_FORGOT_PASSWORD_LINK: 'Forgot Password?',
  ONEMV_REG_HEADER: 'Create Account',
  ONEMV_REG_EMAIL: 'Email',
  ONEMV_REG_EMAIL_PH: 'Email address',
  ONEMV_REG_PASSWORD: 'Password',
  ONEMV_REG_PASSWORD_PH: 'Password',
  ONEMV_REG_VERIFY_PASSWORD: 'Verify Password',
  ONEMV_REG_VERIFY_PASSWORD_PH: 'Verify Password',
  ONEMV_REG_PHONE: 'Phone',
  ONEMV_REG_PHONE_PH: 'Phone',
  ONEMV_REG_REGISTER_BUTTON: 'Register',
  ONEMV_REG_SUCCESS_HEADER: 'Success',
  ONEMV_REG_SUCCESS_MESSAGE: 'Registration Successful!',
  ONEMV_REG_SUCCESS_LOGGING_IN: 'Logging in ...',
  PASSWORD_RECOVERY: 'Password Recovery',
  ONEMV_ACCOUNT_ALREADY_TAKEN: 'One MV Account already used',
  ACCOUNT_CHANGE_PASSWORD: 'Change Password',
  ONEMV_CHANGE_PASSWORD_SUBMIT: 'Change Password',
  ONEMV_CHANGE_PASSWORD_HEADER: 'Change Password',
  PASSWORD_DOES_NOT_MATCH: 'Password does not match',
  ONEMV_EMAIL_DOESNT_MATCH: 'One MV email doesnt match',
  SUBMIT: 'Submit',
  INVALID_EMAIL: 'Invalid Email',
  IN_TRANSIT: 'In-transit',
  YOUR_TRIP_HAS_ARRIVED: 'Your trip has arrived',
  ARRIVED: 'Arrived',
  ESTIMATED_TIME_OF_ARRIVAL: 'Estimated time of arrival',
  PASSWORD_RECOVERY_MESSAGE: 'Password reset instructions will be sent to your email address',
  PASSWORD_RECOVERY_SUCCESS_MESSAGE: 'Password reset instructions has been sent to your registered email:',
  NOT_A_VALID_EMAIL: 'Not a valid email',
  EMAIL_NOT_YET_VERIFIED: 'Email is not yet verified',
  RESET_PASSWORD: 'Reset Password',
  NEW_PASSWORD: 'New Password',
  TYPE_NEW_PASSWORD: 'Type new password',
  RETYPE_NEW_PASSWORD: 'Re-type new password',
  PASSWORD_RESET_SUCCESSFUL: 'Password Reset Successful!',
};
